# Generated by Django 3.2.3 on 2021-06-05 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('education', models.CharField(choices=[('Class-I', 'Class-1'), ('Class-II', 'Class-2'), ('Class-III', 'Class-3')], max_length=255)),
                ('current_address', models.CharField(max_length=255)),
                ('language_known', models.CharField(max_length=255)),
                ('hobbies', models.CharField(max_length=255)),
                ('marks_obtained', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('qualification', models.CharField(choices=[('UG', 'under-graduate'), ('PG', 'Post-graduate'), ('Grd', 'Graduated')], max_length=5)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'female')], max_length=20)),
                ('current_address', models.CharField(max_length=255)),
                ('prefered_working_location', models.CharField(max_length=255)),
                ('prefered_standard', models.CharField(choices=[('PR', 'Primary_standard'), ('MI', 'Middle _standard'), ('SEC', 'Secondary_standard'), ('SSEC', 'Senior_secondary')], max_length=255)),
                ('prefered_subject', models.CharField(choices=[('Science', 'SCIENCE'), ('Mathematics', 'MATHS'), ('Computer Science', 'CSE'), ('Commerce', 'Com'), ('Biology', 'bio'), ('Others', 'oth')], max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
